name: SE 1.5.97 Build

on:
  push:
    branches: '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: powerof3/pack-skse-mod/.github/workflows/build-variant.yml@main-vs2022
    with:
      GIT_BRANCH: ${{ github.ref_name }}
      GIT_COMMON_LIB_BRANCH: ''
      CMAKE_PROJECT_DIR: ''
      CMAKE_CONFIG_PRESET: 'vs2022-se'
      CMAKE_BUILD_PRESET: 'vs2022-se'
      CMAKE_CONFIG: 'Release'
      BINARY_DIR: 'build'
      BINARY_NAME: ''
      BINARY_NAME_VAR: 'NAME'
      BINARY_VERSION: ''
      BINARY_VERSION_VAR: 'VERSION'
      VARIANT: 'se'
